### ISSUE TITLE
delete actionの改良

### ISSUE THREAD

**Issue by Shougo** [thinca/vim-unite-history#1]
今日使っていて気になったので……

現在のdelete actionは

```
let s:action_table = {
\   'delete': {
\     'description': 'delete from history',
\     'is_selectable': 1,
\   },
\ }
```

となっていますが、

```
  \ 'is_invalidate_cache' : 1,
  \ 'is_quit' : 0,
```

も加えたほうが良いかなーと思いました。
実行後終了しないほうが、消えたことが分かりやすいかなと思います。

**Comment by thinca** [comment]
確認なんですが、一般的にdeleteアクションはそのような挙動になっているのでしょうか。
他の delete と挙動が統一されていた方が使ったときに戸惑うことが少ないかと思います。

**Comment by Shougo** [comment]
はい。そうです。他のkindのactionはno_quitになっています。
だからこそ、unite-history/command, searchの挙動に不満を感じたのです。

**Comment by thinca** [comment]
対応しました！

**Comment by Shougo** [comment]
ありがとうございます。
