### ISSUE TITLE
Feature request: Default action for search history

### ISSUE THREAD

**Issue by OliverUv** [thinca/vim-unite-history#2]
Default action for search history items should not be to try to execute them, but to  search in the current file.

**Comment by thinca** [comment]
I think `kind-command` should be fixed.
@Shougo: ping

**Comment by Shougo** [comment]
Thanks. I fixed the problem. Please update unite.vim.

**Comment by OliverUv** [comment]
Everything now works as expected, thanks for the fast action and awesome plugins :)
